env:
  node: true
  es2021: true
  jest: true
parser: '@typescript-eslint/parser'
root: true
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: 'tsconfig.json'
plugins:
  - '@typescript-eslint'
  - prettier
extends: 
  - prettier
rules: {
    '@typescript-eslint/interface-name-prefix': 'off'
    '@typescript-eslint/explicit-function-return-type': 'off'
    '@typescript-eslint/explicit-module-boundary-types': 'off'
    '@typescript-eslint/no-explicit-any': 'off'
}
