apiVersion: v1
kind: Pod
metadata:
  name: authentication
  labels:
    name: authentication
spec:
  containers:
  - name: starter-authentication
    image: cmion/starter-authentication:0.0.1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8000
