version: '3.8'

services: 
    authentication:
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
        restart: unless-stopped
        volumes: 
            - ./src:/home/app/src
            - ./.env:/home/app/.env
            - ./nodemon.json:/home/app/nodemon.json
        container_name: starter_authentication
        expose: 
            - '8000'
        ports: 
            - '8000:8000'
        command: yarn start:dev
        environment: 
            NODE_ENV: development
        links:
            - rabbitmq
        depends_on:
            - rabbitmq
    rabbitmq:
        restart: unless-stopped
        image: rabbitmq:3.8.16
        container_name: rabbitmq
        ports: 
            - 5672:5672
            - 15672:15672